services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    # 添加内存限制，根据您的服务器情况调整
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      - NODE_ENV=production
    # 如果您有其他环境变量，可以在这里添加 