export const language: Record<string, any> = {
  en: {
    hello: "Hello! Welcome!",
    login: "sign in",
    regisit: "sign up",
    username: "username",
    password: "password",
    telephone: "telephone",
    email: "email",
    registrationcode: "registration code",
    registration: "registration",
    myfarm: "My Farm",
    contactus: "Contract",
    latestnews: "News",
    usefulforms: "Usefule Form",
    buymedications: "Buy Medications",
    agreeterms: 'I agree to the above terms',
    home: 'Home',
    userrecord: 'Records', 
    farminformation: 'Info',
    forggetpassword: 'forget the password',
    goodnight: "Good night, Ronald's farm!",
    more: 'more',
    takeorally: 'take orally',
    vaccine: 'vaccine',
    price: 'price',
    search: 'search',
    select: 'select',
    shopCart: 'ShopCart'
  },
  zh: {
    hello: "您好！歡迎登錄",
    login: "登入",
    regisit: "註冊",
    username: "用戶名",
    password: "密碼",
    telephone: "電話",
    email: "電郵",
    registrationcode: "註冊碼",
    registration: "登記",
    myfarm: "我的農場",
    contactus: "聯絡我們",
    latestnews: "最新消息",
    usefulforms: "有用表格",
    buymedications: "購買藥物",
    agreeterms: '我同意以上條款',
    home: '主頁',
    userrecord: '用戶紀錄', 
    farminformation: '農場資料',
    forggetpassword: '忘記密碼',
    goodnight: "晚安，Ronald的農場！",
    more: '查看更多',
    takeorally: '口服',
    vaccine: '疫苗',
    price: '價錢',
    search: '搜尋',
    select: '選擇',
    shopCart: '購物車'
  },
};
