export const language: Record<string, any> = {
  en: {
    hello: "Hello! Welcome!",
    login: "sign in",
    regisit: "sign up",
    username: "username",
    password: "password",
    telephone: "telephone",
    email: "email",
    registrationcode: "registration code",
    registration: "registration",
    myfarm: "My Farm",
    contactus: "Contract",
    latestnews: "News",
    usefulforms: "Usefule Form",
    buymedications: "Buy Medications",
    agreeterms: 'I agree to the above terms',
    home: 'Home',
    userrecord: 'Records', 
    farminformation: 'Info',
    forggetpassword: 'forget the password',
    goodnight: "Good night, Ronald's farm!",
    more: 'more',
    takeorally: 'take orally',
    vaccine: 'vaccine',
    price: 'price',
    search: 'search',
    select: 'select',
    shopCart: 'ShopCart',
    immunity: 'immunity',
    feed: 'Farm feed recipe database',
    chickenbatch: 'Chicken batch database',
    clean: 'Cleaning program database',
    farmhello: "Ronald's farm!",
    farmquota: 'Breeding quota:',
    chickentype: 'Species：',
    cooptype: 'Coop type：',
    seedlings: 'Seedlings:', 
    immunityname: 'Immunity',
    feedname: 'Farm feed recipe',
    chickenbatchname: 'Chicken batch',
    cleanname: 'Cleaning program',
    small: 'small',
    medium: 'medium',
    big: 'big',
    nums: '', 
    batch: 'batch',
    immunizationdate: 'The effective date of this immunization schedule',
    vaccinename:'The name of the vaccine',
    vaccinestrains: 'Vaccine strains',
    vaccinestype: 'Types of vaccines',
    vaccinesage: 'Age of vaccination',
    vaccinationsnums: 'Number of vaccinations',
    administered: 'Dose to be administered',
    vaccinesroute: 'Route of vaccination',
    manufacturers: 'Vaccine manufacturers',
    vaccinewhere: 'Where the vaccine is manufactured',
    clearingdate: 'The effective date of this clearing procedure',
    cleantype:'Type of detergent used',
    rodenticidestype: 'Types of rodenticides used',
    endoparasitic: 'Endoparasitic anthelmintics',
    exoparasitic: 'Exoparasitic anthelmintics',
    insecticide: 'Insecticide',
    feedingdose:'FeedingDose',
    capacity: 'capacity',
    spermdose: 'SpermDose',
  },
  zh: {
    hello: "您好！歡迎登錄",
    login: "登入",
    regisit: "註冊",
    username: "用戶名",
    password: "密碼",
    telephone: "電話",
    email: "電郵",
    registrationcode: "註冊碼",
    registration: "登記",
    myfarm: "我的農場",
    contactus: "聯絡我們",
    latestnews: "最新消息",
    usefulforms: "有用表格",
    buymedications: "購買藥物",
    agreeterms: '我同意以上條款',
    home: '主頁',
    userrecord: '用戶紀錄', 
    farminformation: '農場資料',
    forggetpassword: '忘記密碼',
    goodnight: "晚安，Ronald的農場！",
    more: '查看更多',
    takeorally: '口服',
    vaccine: '疫苗',
    price: '價錢',
    search: '搜尋',
    select: '選擇',
    shopCart: '購物車',
    immunity: '免疫程序资料库',
    feed: '農場饲料配方资料库',
    chickenbatch: '雞隻批次资料库',
    clean: '清潔程序资料库',
    farmhello: 'Ronald的農場！',
    farmquota: '注冊養殖額度:',
    chickentype: '雞隻種類：',
    cooptype: '雞舍種類：',
    seedlings: '雞苗:',
    immunityname: '免疫程序',
    feedname: '農場饲料配方',
    chickenbatchname: '雞隻批次资料',
    cleanname: '清潔程序',
    small: '雞苗',
    medium: '中雞',
    big: '大雞', 
    nums: '隻', 
    batch: '批次',
    immunizationdate: '本免疫程序有效日期',
    vaccinename:'疫苗名稱',
    vaccinestrains: '疫苗毒株',
    vaccinestype: '疫苗種類',
    vaccinesage: '接種日龄',
    vaccinationsnums: '接種次數',
    administered: '接種劑量',
    vaccinesroute: '接種途徑',
    manufacturers: '疫苗製造商',
    vaccinewhere: '疫苗製造地',
    clearingdate: '本清程序有效日期',
    cleantype:'清潔劑使用種類',
    rodenticidestype: '滅鼠劑使用種類',
    endoparasitic: '内寄生蟲驅蟲藥',
    exoparasitic: '外寄生蟲驅蟲藥',
    insecticide: '殺蟲劑',
    feedingdose:'饲料用量',
    capacity: '料倉及穀倉容量',
    spermdose: '精料用量',
  },
};
