export const language: Record<string, any> = {
  en: {
    hello: "Hello! Welcome!",
    login: "Sign In",
    regisit: "Sign Up",
    username: "Username",
    password: "Password",
    repassword: 'Re-enter Password',
    telephone: "Phone Number",
    email: "Email",
    registrationcode: "registration code",
    farmname: 'Name of the Farm',
    registration: "Register",
    myfarm: "My Farm",
    contactus: "Contact Us",
    latestnews: "News",
    usefulforms: "Useful Form",
    buymedications: "OHRP Pharmacy",
    agreeterms: 'I agree to the above terms',
    home: 'Home',
    userrecord: 'Records', 
    farminformation: 'Info',
    forggetpassword: 'forget password?',
    goodnight: "Hello, Ronald's farm!",
    more: 'more',
    takeorally: 'Oral Medicine',
    vaccine: 'Vaccination',
    price: 'Price',
    search: 'Search',
    select: 'select',
    shopCart: 'ShopCart',
    immunity: 'immunity',
    feed: 'Farm feed recipe database',
    chickenbatch: 'Chicken batch database',
    clean: 'Cleaning program database',
    farmhello: "Ronald's farm!",
    farmquota: 'Breeding quota:',
    chickentype: 'Species:',
    cooptype: 'Coop type:',
    seedlings: 'Seedlings:', 
    immunityname: 'Immunity',
    feedname: 'Farm feed recipe',
    chickenbatchname: 'Chicken batch',
    cleanname: 'Cleaning program',
    small: 'small',
    medium: 'medium',
    big: 'big',
    nums: '', 
    batch: 'batch',
    immunizationdate: 'The effective date of this immunization schedule',
    vaccinename:'The status of the vaccine',
    vaccinestrains: 'Vaccine strains',
    vaccinestype: 'Types of vaccines',
    vaccinesage: 'Age of vaccination',
    vaccinationsnums: 'Number of vaccinations',
    administered: 'Dose to be administered',
    vaccinesroute: 'Route of vaccination',
    manufacturers: 'Vaccine manufacturers',
    vaccinewhere: 'Where the vaccine is manufactured',
    clearingdate: 'The effective date of this clearing procedure',
    cleantype:'Type of detergent used',
    rodenticidestype: 'Types of rodenticides used',
    endoparasitic: 'Endoparasitic anthelmintics',
    exoparasitic: 'Exoparasitic anthelmintics',
    insecticide: 'Insecticide',
    feedingdose:'FeedingDose',
    capacity: 'capacity',
    spermdose: 'SpermDose',
    feedsmonth: 'The number of mixed feeds per month',
    feedermixers: 'The number of feeder mixers',
    mixercapacity: 'Chicken fry feed mixer capacity',
    mediumcapacity: 'Medium to large chicken feeder capacity',
    chickenmixercapacity: 'Chicken mixer capacity',
    towercapacity:'Tower capacity',
    amountdressing: 'The amount of material tower dressing',
    numberfeedmixer: 'The number of cleaning times per month for the feed mixer',
    numbercleaned: 'The number of times the tower is cleaned per month',
    dateinput: 'Input date',
    addchicken: 'Add New Flock',
    batchname: 'Batch name',
    incubationdate: 'Incubation date',
    chickentotal: 'Total number of chickens',
    chickenseedlingsupplier: 'Chicken seedling supplier',
    mortality: 'Mortality',
    medicationrecords: 'Medication records',
    feedtab0name0: 'Monthly usage of seedling concentrate',
    feedtab0name1: 'Monthly usage of refined materials',
    feedtab0name2: 'Monthly usage of high precision materials',
    feedtab0name3: 'Monthly borrowing of mother refined ingredients',
    feedtab0name4: 'Monthly usage of egg mother refined ingredients',
    feedtab0name5: 'Monthly usage of refined materials',
    feedtab2name0: 'Monthly seedling material usage',
    feedtab2name1: 'Monthly usage of Zhongya materials',
    feedtab2name2: 'Monthly large amount of material application',
    feedtab2name3: "Monthly usage of copper material for mother's daughter",
    feedtab2name4: 'Monthly consumption of Longdan mother feed',
    feedtab2name5: 'Monthly usage of public materials',
    addshop: 'add product',
    shopname: 'Name',
    shopprice: 'Price',
    shopresources_id: 'Img',
    shopremarks: 'Remarks',
    shptype: 'Product type',
    logout: 'Logout',
    animalstab0name0: 'The total number of chickens',
    animalstab0name1: 'Chicken Age',
    animalstab0name2: 'Number of dead chickens',
    animalstab0name3: 'Number of eliminated chickens',
    animalstab1name0: 'Batch name/number',
    animalstab1name1: 'Drug name',
    animalstab1name2: 'Drug dose',
    animalstab1name2unit: 'Milligrams',
    animalstab1name3: "Drug dosage",
    animalstab1name3unit: 'Milliliters',
    animalstab1name4: 'Number of medication days',
    animalstab1name4unit: 'Day',
    questionA: "A. Score 5 points for each “yes” answer.",
    questionA0: "My farm is isolated from other poultry facilities.",
    questionA1:
      "My poultry houses are set back at least 200 feet from public roads.",
    questionA2:
      "Access deterrents are in place such as warning signs at entrances, perimeter fencing or gated driveways. ",
    questionA3: "My buildings are secured with locks.",
    questionA4: "My employees do not own poultry.",
    questionA5: "No other avian species are kept on my property.",
    questionA6:
      "I have a pest management programme to control mice, rats and other pests.",
    questionB: "B. Score 4 points for each “yes” answer.",
    questionB0:
      "My birds are observed every day for abnormal symptoms and overall flock health.",
    questionB1:
      "I routinely analyze my poultry production, feed consumption, and mortality records for signs of problems.",
    questionB2:
      "Dead birds are picked up daily from the houses for appropriate disposal.",
    questionB3:
      "My farm has secure dead bird disposal, with no access to birds or animals.",
    questionB4:
      "Vehicles or people cannot enter my farm or poultry houses without my permission or knowledge.",
    questionB5:
      "Visitors must park vehicles in a designated area and sign a logbook.",
    questionC: "C. Score 3 points for each “yes” answer.",
    questionC0: "My poultry housing is animal and wild-bird proof.",
    questionC1:
      "All tools and equipment are cleaned and disinfected before coming on my farm.",
    questionC2:
      "Production houses are thoroughly cleaned and disinfected between flocks.",
    questionC3:
      "Production house entryways are routinely cleaned and disinfected.",
    questionC4:
      "Disinfectant footbaths are at each entryway of every facility and are routinely cleaned and recharged",
    questionC5:
      "Debris and vegetation are cleaned up and kept clear of the production facilities.",
    questionC6: "Feed spills are cleaned up quickly when they occur.",
    questionC7: "For necessary visitors, I provide clean coveralls and boots.",
    questionC8:
      "My employees do not travel to other poultry premises not under my control.",
    questionD: "D. Score 2 points for each “yes” answer.",
    questionD0:
      "All utility and service vehicles entering my farm are properly sanitized before entry and the drivers do not enter the poultry houses.",
    questionD1:
      "Farm employees work only in assigned areas; they do not go to other areas of the farm.",
    questionD2: "Dead birds are not carried from house to house.",
    questionD3:
      "Poultry waste from other farms is never spread on the fields adjacent to my farm.",
    questionD4:
      "I have instructed my employees and service personnel about poultry disease and on-farm prevention measures.",
    questionE: "E. Score 1 points for each “yes” answer.",
    questionE0: "Household pets are kept away from the poultry buildings.",
    questionE1: "I have implemented a fly control programme for my farm.",
    questionE2:
      "I follow all company-implemented disease prevention measures on my farm.",
    questionE3:
      "I regularly attend educational programmes to keep abreast of new developments in disease control.",
    submit: "submit",
    questionnaire: 'Questionnaire',
  },
  zh: {
    hello: "您好！歡迎登錄",
    login: "登入",
    regisit: "註冊",
    username: "用戶名",
    password: "密碼",
    repassword: '再次輸入密碼',
    telephone: "電話",
    email: "電郵",
    registrationcode: "註冊碼",
    registration: "登記",
    farmname: '農場名稱',
    myfarm: "我的農場",
    contactus: "聯絡我們",
    latestnews: "最新消息",
    usefulforms: "有用表格",
    buymedications: "購買藥物",
    agreeterms: '我同意以上條款',
    home: '主頁',
    userrecord: '用戶紀錄', 
    farminformation: '農場資料',
    forggetpassword: '忘記密碼',
    goodnight: "您好，Ronald的農場！",
    more: '查看更多',
    takeorally: '口服',
    vaccine: '疫苗',
    price: '價錢',
    search: '搜尋',
    select: '選擇',
    shopCart: '購物車',
    immunity: '免疫程序資料庫',
    feed: '農場飼料配方資料庫',
    chickenbatch: '雞隻批次資料庫',
    clean: '清潔程序資料庫',
    farmhello: 'Ronald的農場！',
    farmquota: '注冊養殖額度:',
    chickentype: '雞隻種類：',
    cooptype: '雞舍種類：',
    seedlings: '雞苗:',
    immunityname: '免疫程序',
    feedname: '農場飼料配方',
    chickenbatchname: '雞隻批次資料',
    cleanname: '清潔程序',
    small: '雞苗',
    medium: '中雞',
    big: '大雞', 
    nums: '隻', 
    batch: '批次',
    immunizationdate: '本免疫程序有效日期',
    vaccinename:'疫苗狀態',
    vaccinestrains: '疫苗毒株',
    vaccinestype: '疫苗種類',
    vaccinesage: '接種日龄',
    vaccinationsnums: '接種次數',
    administered: '接種劑量',
    vaccinesroute: '接種途徑',
    manufacturers: '疫苗製造商',
    vaccinewhere: '疫苗製造地',
    clearingdate: '本清程序有效日期',
    cleantype:'清潔劑使用種類',
    rodenticidestype: '滅鼠劑使用種類',
    endoparasitic: '内寄生蟲驅蟲藥',
    exoparasitic: '外寄生蟲驅蟲藥',
    insecticide: '殺蟲劑',
    feedingdose:'飼料用量',
    capacity: '料倉及穀倉容量',
    spermdose: '精料用量',
    feedsmonth: '每月混合飼料次數',
    feedermixers: '飼料混合器數量',
    mixercapacity: '雞苗飼料混合器容量',
    mediumcapacity: '中雞至大雞飼料混合器容量',
    chickenmixercapacity: '大雞飼料混合器容量',
    towercapacity:'料塔容量',
    amountdressing: '料塔敷量',
    numberfeedmixer: '每月飼料混合器清潔次數',
    numbercleaned: '每月料塔清潔次數',
    dateinput: '輸入日期',
    addchicken: '加入雞群',
    batchname: '批次名稱',
    incubationdate: '出孵日期',
    chickentotal: '本批入雞總數',
    chickenseedlingsupplier: '雞苗供應商',
    mortality: '死淘率',
    medicationrecords: '用藥記錄',
    feedtab0name0: '每月苗精料用量',
    feedtab0name1: '每月中精料用量',
    feedtab0name2: '每月大精料用量',
    feedtab0name3: '每月後借母雅精料用量',
    feedtab0name4: '每月座蛋母雅精料用量',
    feedtab0name5: '每月公精料用量',
    feedtab2name0: '每月苗料用量',
    feedtab2name1: '每月中雅料用量',
    feedtab2name2: '每月大料敷量',
    feedtab2name3: "每月後母雅铜料用量",
    feedtab2name4: '每月隆蛋母料用量',
    feedtab2name5: '每月公料用量',
    addshop: '新增商品',
    shopname: '商品名稱',
    shopprice: '商品價格',
    shopresources_id: '商品圖片',
    shopremarks: '商品備註',
    shptype: '商品類别',
    logout: '登出',
    animalstab0name0: '本批入雞總數量',
    animalstab0name1: '雞隻日齡',
    animalstab0name2: '死亡雞隻數量',
    animalstab0name3: '淘汰雞隻數量',
    animalstab1name0: '批次名稱/編號',
    animalstab1name1: '藥物名稱',
    animalstab1name2: '藥物劑量',
    animalstab1name2unit: '毫克',
    animalstab1name3: "藥物用量",
    animalstab1name3unit: '毫升',
    animalstab1name4: '用藥日數',
    animalstab1name4unit: '日',
    questionA: "A. Score 5 points for each “yes” answer.",
    questionA0: "我的農場與其它雞場有很好的隔離",
    questionA1: "我的雞舍與公路至少有200英尺的距離",
    questionA2: "出入口處有不准進入的標識，有圍牆及閘門",
    questionA3: "我的建築物可安全的鎖上",
    questionA4: "我的飼養員沒有自養雞隻",
    questionA5: "雞舍裡沒有其他禽類",
    questionA6: "我場裡有老鼠或其他蟲害的控制",
    questionB: "B. Score 4 points for each “yes” answer.",
    questionB0: "我每天觀察雞群是否有不正常的症狀和總體健康情況",
    questionB1: "我經常分析雞群生產性能，採食情況和死淘記錄，以及早發現問題",
    questionB2: "每天死雞均會從雞舍撿起並合適丟棄處理",
    questionB3: "我場的死雞處理嚴密，不會使其它雞或動物接觸到",
    questionB4: "車輛或人員沒我的允許不可以進入雞場",
    questionB5: "訪客必須在指定區停車及簽拜訪記錄冊",
    questionC: "C. Score 3 points for each “yes” answer.",
    questionC0: "我的雞舍其它動物和野鳥無法進入",
    questionC1: "所有的工具和設備均洗淨和消毒後才回到我的農場",
    questionC2: "生產車間在批次間均經過徹底清洗和消毒",
    questionC3: "生產車間的通道經常清洗和消毒",
    questionC4: "每個車間入口處均備有水鞋消毒池，並經常更新和清洗",
    questionC5: "在生產車間殘渣和植物有被經常清理及清空",
    questionC6: "撒落的飼料會及時處理",
    questionC7: "對需要的訪客，我會提供乾淨的保護衣物及水鞋",
    questionC8: "我的顧員不會去非我控制的其它雞場",
    questionD: "D. Score 2 points for each “yes” answer.",
    questionD0: "所有的用品和服務車輛在進場前都經過適當消毒，司機不會進入雞舍",
    questionD1: "所有的用品和服務車輛在進場前都經過適當消毒，司機不會進入雞舍",
    questionD2: "死雞不會在雞舍間串流",
    questionD3: "其它雞場的雞場廢棄物從不會在我場隔壁",
    questionD4:
      "我明確地指示我的工作人員和進場服務人員有關我雞場的現場禽病預防措施",
    questionE: "E. Score 1 points for each “yes” answer.",
    questionE0: "寵物與雞舍隔離",
    questionE1: "我的雞場有良好的蒼蠅控制計畫",
    questionE2: "我的雞舍貫徹執行全場疾病控制措施",
    questionE3: "我經常參與培訓令自己跟上對疾病控制的新發展",
    submit: "提交",
    questionnaire: '問卷',
  },
};
